/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(phase_shifting_windowing_vcc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2aaae72158b45c76ce5448e4a067c88e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/FDC/phase_shifting_windowing_vcc.h>
// pydoc.h is automatically generated in the build directory
#include <phase_shifting_windowing_vcc_pydoc.h>

void bind_phase_shifting_windowing_vcc(py::module& m)
{

    using phase_shifting_windowing_vcc    = ::gr::FDC::phase_shifting_windowing_vcc;


    py::class_<phase_shifting_windowing_vcc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<phase_shifting_windowing_vcc>>(m, "phase_shifting_windowing_vcc", D(phase_shifting_windowing_vcc))

        .def(py::init(&phase_shifting_windowing_vcc::make),
           py::arg("blocklen"),
           py::arg("numphasestates"),
           py::arg("shifts"),
           py::arg("passbw"),
           py::arg("stopbw"),
           py::arg("windowtype"),
           D(phase_shifting_windowing_vcc,make)
        )
        



        ;




}








