/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_cut_vxx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3ec047d805f51d20cd5091730deae79f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/FDC/vector_cut_vxx.h>
// pydoc.h is automatically generated in the build directory
#include <vector_cut_vxx_pydoc.h>

void bind_vector_cut_vxx(py::module& m)
{

    using vector_cut_vxx    = ::gr::FDC::vector_cut_vxx;


    py::class_<vector_cut_vxx, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<vector_cut_vxx>>(m, "vector_cut_vxx", D(vector_cut_vxx))

        .def(py::init(&vector_cut_vxx::make),
           py::arg("itemsize"),
           py::arg("veclen"),
           py::arg("offset"),
           py::arg("blocklen"),
           D(vector_cut_vxx,make)
        )
        



        ;




}








